name: test
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        usage:
          - keep
          - exclude
          - require label
        value:
          - 1
          - 2
        exclude:
          - usage: exclude
            value: 1
          - usage: exclude
            value: 2

          - usage: require label
            ignore exclusion: >-
              ${{ github.event_name != 'pull_request'
               || contains(github.event.pull_request.labels.*.name, 'marker')
               || contains(github.event.pull_request.labels.*.name, 'mark 2')
               }}
        ignore exclusion:
          - false
    steps:
      - name: Step 1
        env:
          value: ${{matrix['two words']}}
        run: echo "$value"
