# Github actions workflow
name: test
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Try different multiline string styles to see if they work.
      - name: Literal clip
        run: |
          echo these are
          echo separate lines
      - name: Literal strip
        run: |-
          echo these are
          echo separate lines
      - name: Folded clip
        run: >
          echo this should
          all be one line
      - name: Folded strip
        run: >-
          echo this should
          all be one line
