name: test
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        two words:
          - val1
          - val2
    steps:
      - name: Step 1
        env:
          value: ${{matrix['two words']}}
        run: echo "$value"
